spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_smart_classroom
    username: postgres
    password: 23FE1A0424

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    com.finalYear: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.flywaydb: INFO

server:
  port: 8080

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:4200

mqtt:
  broker-url: tcp://localhost:1883

springdoc:
  swagger-ui:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always