package com.finalYear.smartClassRoom.ai.model;

import lombok.*;

import java.util.List;
import java.util.Map;

/**
 * Standardised response returned by every AI Agent.
 * Supports text answers, video recommendations, data, and future TTS.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AgentResponse {

    /** The primary text answer */
    private String answer;

    /** Agent that produced this response */
    private String agentName;

    /** Whether the response was generated by Ollama or built-in KB */
    @Builder.Default
    private boolean ollamaGenerated = false;

    /** Future: recommended videos */
    @Builder.Default
    private List<VideoRecommendation> videos = List.of();

    /** Future: structured data (e.g., table of marks, attendance rows) */
    private Map<String, Object> data;

    /** Future: follow-up questions the AI suggests */
    @Builder.Default
    private List<String> followUpQuestions = List.of();

    /** Future: audio URL for TTS output */
    private String audioUrl;

    /** Tokens used */
    @Builder.Default
    private int tokensUsed = 0;

    // ── Convenience factory ───────────────────────────────────────────────────
    public static AgentResponse text(String answer, String agentName) {
        return AgentResponse.builder()
                .answer(answer)
                .agentName(agentName)
                .build();
    }

    public static AgentResponse ollama(String answer, String agentName) {
        return AgentResponse.builder()
                .answer(answer)
                .agentName(agentName)
                .ollamaGenerated(true)
                .build();
    }

    // ── Inner classes ─────────────────────────────────────────────────────────
    @Data @AllArgsConstructor @NoArgsConstructor
    public static class VideoRecommendation {
        private String title;
        private String url;
        private String thumbnail;
        private String duration;
    }
}
