package com.finalYear.smartClassRoom.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

@Entity
@Table(
        name = "student_faces",
        indexes = {
                @Index(name = "idx_student_face_student",    columnList = "student_id"),
                @Index(name = "idx_student_face_angle",      columnList = "angle_type"),
                @Index(name = "idx_student_face_captured_by", columnList = "captured_by_teacher_id")
        }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@ToString(exclude = {"student", "capturedByTeacher"})
@EqualsAndHashCode(of = "id")
public class StudentFace implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(
            name = "student_id",
            nullable = false,
            foreignKey = @ForeignKey(name = "fk_student_face_student")
    )
    private Student student;

    /** Absolute or relative path of the saved face image */
    @Column(name = "image_path", nullable = false, length = 500)
    private String imagePath;

    /** Path to the .pkl / .npy encoding file generated by Python */
    @Column(name = "encoding_path", length = 500)
    private String encodingPath;

    @Enumerated(EnumType.STRING)
    @Column(name = "angle_type", nullable = false, length = 20)
    private AngleType angleType;

    /** Teacher who performed the face capture session */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(
            name = "captured_by_teacher_id",
            foreignKey = @ForeignKey(name = "fk_face_captured_by")
    )
    private Teacher capturedByTeacher;

    /** Date/time when the face was captured */
    @Column(name = "capture_date")
    private LocalDateTime captureDate;

    /** face_recognition library confidence score (lower = better match) */
    @Column(name = "face_confidence")
    private Double faceConfidence;

    /** Number of images captured in this session */
    @Column(name = "total_images")
    private Integer totalImages;

    @Builder.Default
    @Column(name = "is_active", nullable = false)
    private boolean active = true;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    public enum AngleType {
        FRONT,
        LEFT,
        RIGHT,
        UP,
        DOWN
    }
}